---

- name: add EPEL repo on CentOS
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
  tags: [ mitogen, epel ]

- name: pip install setuptools
  pip:
    name: setuptools
    state: present
  tags: [ mitogen, pip ]

- name: pip install mitogen
  pip:
    name: mitogen
    umask: '{{ set_umask }}'
    state: present
  tags: [ mitogen, install ]
